// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2luo9mo1ShyfRg9qz3tKced3NdiGdVfU',
    appId: '1:259408385272:web:75abc6c9039f29d8b2970d',
    messagingSenderId: '259408385272',
    projectId: 'nilinde-d567a',
    authDomain: 'nilinde-d567a.firebaseapp.com',
    storageBucket: 'nilinde-d567a.appspot.com',
    measurementId: 'G-HK64G2D027',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHF7xP7XDvp_D5hY0Qic5Xrumr9VvMqFk',
    appId: '1:259408385272:android:b5e6fa5b14b6aa5db2970d',
    messagingSenderId: '259408385272',
    projectId: 'nilinde-d567a',
    storageBucket: 'nilinde-d567a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZ1C4i19Yap-t0hNFyedQ7lzQVSZ_obI',
    appId: '1:259408385272:ios:bfe703a3d048e304b2970d',
    messagingSenderId: '259408385272',
    projectId: 'nilinde-d567a',
    storageBucket: 'nilinde-d567a.appspot.com',
    iosClientId: '259408385272-8022og2sb9hger4a3j70abpouirshnlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nilinde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZ1C4i19Yap-t0hNFyedQ7lzQVSZ_obI',
    appId: '1:259408385272:ios:bfe703a3d048e304b2970d',
    messagingSenderId: '259408385272',
    projectId: 'nilinde-d567a',
    storageBucket: 'nilinde-d567a.appspot.com',
    iosClientId: '259408385272-8022og2sb9hger4a3j70abpouirshnlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nilinde',
  );
}
